<a href="https://colab.research.google.com/github/Kaly2004/Kaly2004/blob/main/pythonnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

import numpy is used for import numerical value.
call np to activate the function

In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
a+b
type(a)
type(b)

numpy.ndarray

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype



dtype('int64')

In [ ]:
arr=np.array([1,3,4,5,2+3j])
print(arr)
print(arr.shape)
print(arr.dtype)


[1.+0.j 3.+0.j 4.+0.j 5.+0.j 2.+3.j]
(5,)
complex128


In [ ]:
arr=np.array([1,3.5,4,5,2+3j])
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3.5+0.j 4. +0.j 5. +0.j 2. +3.j]
(5,)
complex128


In [ ]:
arr=np.array( [1,3,4.5,5,2+3j, True] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3. +0.j 4.5+0.j 5. +0.j 2. +3.j 1. +0.j]
(6,)
complex128


In [ ]:
arr=np.array( [1,3,4.5,5,2+3j, False] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3. +0.j 4.5+0.j 5. +0.j 2. +3.j 0. +0.j]
(6,)
complex128


In [ ]:
arr=np.array([1,3,4.5,5,2+3j,True,"abhi"])
print(arr)
print(arr.shape)
print(arr.dtype)

['1' '3' '4.5' '5' '(2+3j)' 'True' 'abhi']
(7,)
<U64


In [11]:
import numpy as np
arr=np.array( [ [1,2,3] , [4,5,6] , [8,None,None] ] )
arr


array([[1, 2, 3],
       [4, 5, 6],
       [8, None, None]], dtype=object)

In [12]:
arr.shape

(3, 3)

In [19]:
np.ones( (2,4) )
np.zeros( (2,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
import numpy as np
arr=np.array( [[1,2,3,4,5], [5,6,7,8,9] ,[10,11,12,13,14] ,[15,16,17,18,19] ] )
arr


array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:

arr.min()


1

In [38]:

arr.sum()

195

In [34]:

arr.mean()

9.75

In [35]:

arr.std()

5.448623679425842

In [39]:
arr.max()

19

In [59]:
for row in arr:
  print(row.sum())

15
35
60
85


In [60]:
for row in arr:
  print(row.min())

1
5
10
15


In [61]:
for row in arr:
  print(row.mean())

3.0
7.0
12.0
17.0


In [62]:
for row in arr:
  print(row.std())

1.4142135623730951
1.4142135623730951
1.4142135623730951
1.4142135623730951


In [63]:
for row in arr:
  print(row.sum())

15
35
60
85


In [64]:
for column in arr:
  print(column.sum())

15
35
60
85


In [65]:
for column in arr:
  print(column.min())

1
5
10
15


In [66]:
for column in arr:
  print(column.mean())

3.0
7.0
12.0
17.0


In [67]:
for column in arr:
  print(column.max())

5
9
14
19


In [75]:
row_sums=np.sum(arr,axis=0)
print(row_sums)

[31 35 39 43 47]


In [74]:
row_min=np.min(arr,axis=0)
print(row_min)

[1 2 3 4 5]


In [76]:
row_max=np.max(arr,axis=0)
print(row_max)

[15 16 17 18 19]


In [77]:
row_mean=np.mean(arr,axis=0)
print(row_mean)

[ 7.75  8.75  9.75 10.75 11.75]


In [78]:
row_std=np.std(arr,axis=0)
print(row_std)

[5.26189129 5.26189129 5.26189129 5.26189129 5.26189129]


In [79]:
col_max=np.max(arr,axis=1)
print(col_max)

[ 5  9 14 19]


In [80]:
col_min=np.min(arr,axis=1)
print(col_min)

[ 1  5 10 15]


In [81]:
col_mean=np.mean(arr,axis=1)
print(col_mean)

[ 3.  7. 12. 17.]


In [83]:
col_std=np.std(arr,axis=1)
print(col_std)


[1.41421356 1.41421356 1.41421356 1.41421356]


In [84]:
col_sum=np.sum(arr,axis=1)
print(col_sum)

[15 35 60 85]
