<a href="https://colab.research.google.com/github/Kaly2004/Kaly2004/blob/main/pythonnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

import numpy is used for import numerical value.
call np to activate the function

In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
a+b
type(a)
type(b)

numpy.ndarray

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype



dtype('int64')

In [ ]:
arr=np.array([1,3,4,5,2+3j])
print(arr)
print(arr.shape)
print(arr.dtype)


[1.+0.j 3.+0.j 4.+0.j 5.+0.j 2.+3.j]
(5,)
complex128


In [ ]:
arr=np.array([1,3.5,4,5,2+3j])
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3.5+0.j 4. +0.j 5. +0.j 2. +3.j]
(5,)
complex128


In [ ]:
arr=np.array( [1,3,4.5,5,2+3j, True] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3. +0.j 4.5+0.j 5. +0.j 2. +3.j 1. +0.j]
(6,)
complex128


In [ ]:
arr=np.array( [1,3,4.5,5,2+3j, False] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3. +0.j 4.5+0.j 5. +0.j 2. +3.j 0. +0.j]
(6,)
complex128


In [ ]:
arr=np.array([1,3,4.5,5,2+3j,True,"abhi"])
print(arr)
print(arr.shape)
print(arr.dtype)

['1' '3' '4.5' '5' '(2+3j)' 'True' 'abhi']
(7,)
<U64


In [11]:
import numpy as np
arr=np.array( [ [1,2,3] , [4,5,6] , [8,None,None] ] )
arr


array([[1, 2, 3],
       [4, 5, 6],
       [8, None, None]], dtype=object)

In [12]:
arr.shape

(3, 3)

In [19]:
np.ones( (2,4) )
np.zeros( (2,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
import numpy as np
arr=np.array( [[1,2,3,4,5], [5,6,7,8,9] ,[10,11,12,13,14] ,[15,16,17,18,19] ] )
arr


array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:

arr.min()


1

In [38]:

arr.sum()

195

In [34]:

arr.mean()

9.75

In [35]:

arr.std()

5.448623679425842

In [39]:
arr.max()

19

In [41]:
for row in arr:
  print(row)
  print(row.sum())

[1 2 3 4 5]
15
[5 6 7 8 9]
35
[10 11 12 13 14]
60
[15 16 17 18 19]
85


In [45]:
for row in arr:
  print(row)
  print(row.min())

[1 2 3 4 5]
1
[5 6 7 8 9]
5
[10 11 12 13 14]
10
[15 16 17 18 19]
15


In [43]:
for row in arr:
  print(row)
  print(row.mean())

[1 2 3 4 5]
3.0
[5 6 7 8 9]
7.0
[10 11 12 13 14]
12.0
[15 16 17 18 19]
17.0


In [44]:
for row in arr:
  print(row)
  print(row.std())

[1 2 3 4 5]
1.4142135623730951
[5 6 7 8 9]
1.4142135623730951
[10 11 12 13 14]
1.4142135623730951
[15 16 17 18 19]
1.4142135623730951


In [46]:
for row in arr:
  print(row)
  print(row.sum())

[1 2 3 4 5]
15
[5 6 7 8 9]
35
[10 11 12 13 14]
60
[15 16 17 18 19]
85


In [47]:
for column in arr:
  print(column)
  print(column.sum())

[ 1  5 10 15]
31
[ 2  6 11 16]
35
[ 3  7 12 17]
39
[ 4  8 13 18]
43
[ 5  9 14 19]
47


In [49]:
for column in arr:
  print(column)
  print(column.min())

[1 2 3 4 5]
1
[5 6 7 8 9]
5
[10 11 12 13 14]
10
[15 16 17 18 19]
15


In [50]:
for column in arr:
  print(column)
  print(column.mean())

[1 2 3 4 5]
3.0
[5 6 7 8 9]
7.0
[10 11 12 13 14]
12.0
[15 16 17 18 19]
17.0


In [56]:
for column in arr:
  print(column)
  print(column.max())

[1 2 3 4 5]
5
[5 6 7 8 9]
9
[10 11 12 13 14]
14
[15 16 17 18 19]
19


In [57]:
row_sums=np.sum(arr,axis=1)
print(row_sums)

[15 35 60 85]


In [58]:
row_min=np.min(arr,axis=1)
print(row_min)

[ 1  5 10 15]
